package com.bwsw.sj.crud.rest.model.instance.response

import com.bwsw.sj.common.dal.model.instance.{ExecutionPlan, FrameworkStage}

class BatchInstanceApiResponse(moduleName: String,
                               moduleVersion: String,
                               moduleType: String,
                               stage: FrameworkStage,
                               status: String,
                               name: String,
                               description: String,
                               parallelism: Any,
                               options: Map[String, Any],
                               perTaskCores: Double,
                               perTaskRam: Int,
                               jvmOptions: Map[String, String],
                               nodeAttributes: Map[String, String],
                               coordinationService: String,
                               environmentVariables: Map[String, String],
                               performanceReportingInterval: Long,
                               engine: String,
                               restAddress: String,
                               val inputs: Array[String],
                               val window: Int,
                               val slidingInterval: Int,
                               val outputs: Array[String],
                               val executionPlan: ExecutionPlan,
                               val startFrom: String,
                               val stateManagement: String,
                               val stateFullCheckpoint: Int,
                               val eventWaitIdleTime: Long,
                               val inputAvroSchema: Map[String, Any])
  extends InstanceApiResponse(
    moduleName,
    moduleVersion,
    moduleType,
    stage,
    status,
    name,
    description,
    parallelism,
    options,
    perTaskCores,
    perTaskRam,
    jvmOptions,
    nodeAttributes,
    coordinationService,
    environmentVariables,
    performanceReportingInterval,
    engine,
    restAddress)
