package com.bwsw.sj.crud.rest.model.instance.response

import com.bwsw.sj.common.dal.model.instance.{FrameworkStage, InputTask}

class InputInstanceApiResponse(moduleName: String,
                               moduleVersion: String,
                               moduleType: String,
                               stage: FrameworkStage,
                               status: String,
                               name: String,
                               description: String,
                               parallelism: Any,
                               options: Map[String, Any],
                               perTaskCores: Double,
                               perTaskRam: Int,
                               jvmOptions: Map[String, String],
                               nodeAttributes: Map[String, String],
                               coordinationService: String,
                               environmentVariables: Map[String, String],
                               performanceReportingInterval: Long,
                               engine: String,
                               restAddress: String,
                               val outputs: Array[String],
                               val checkpointMode: String,
                               val checkpointInterval: Long,
                               val duplicateCheck: Boolean,
                               val lookupHistory: Int,
                               val queueMaxSize: Int,
                               val defaultEvictionPolicy: String,
                               val evictionPolicy: String,
                               val backupCount: Int,
                               val asyncBackupCount: Int,
                               val tasks: Map[String, InputTask])
  extends InstanceApiResponse(
    moduleName,
    moduleVersion,
    moduleType,
    stage,
    status,
    name,
    description,
    parallelism,
    options,
    perTaskCores,
    perTaskRam,
    jvmOptions,
    nodeAttributes,
    coordinationService,
    environmentVariables,
    performanceReportingInterval,
    engine,
    restAddress)
