package com.bwsw.sj.crud.rest.model.instance.response

import com.bwsw.sj.common.dal.model.instance.{ExecutionPlan, FrameworkStage}

class OutputInstanceApiResponse(moduleName: String,
                                moduleVersion: String,
                                moduleType: String,
                                stage: FrameworkStage,
                                status: String,
                                name: String,
                                description: String,
                                parallelism: Any,
                                options: Map[String, Any],
                                perTaskCores: Double,
                                perTaskRam: Int,
                                jvmOptions: Map[String, String],
                                nodeAttributes: Map[String, String],
                                coordinationService: String,
                                environmentVariables: Map[String, String],
                                performanceReportingInterval: Long,
                                engine: String,
                                restAddress: String,
                                val checkpointMode: String,
                                val checkpointInterval: Long,
                                val executionPlan: ExecutionPlan,
                                val startFrom: String,
                                val input: String,
                                val output: String,
                                val inputAvroSchema: Map[String, Any])
  extends InstanceApiResponse(
    moduleName,
    moduleVersion,
    moduleType,
    stage,
    status,
    name,
    description,
    parallelism,
    options,
    perTaskCores,
    perTaskRam,
    jvmOptions,
    nodeAttributes,
    coordinationService,
    environmentVariables,
    performanceReportingInterval,
    engine,
    restAddress)
