package com.bwsw.sj.common.module.reporting

import java.util.Calendar
import java.util.concurrent.locks.ReentrantLock

import scala.collection.mutable

class OutputStreamingPerformanceMetrics(taskId: String, host: String, inputStreamName: String, outputStreamName: String)
  extends PerformanceMetrics(taskId, host, Array(inputStreamName), Array(outputStreamName)) {

  val mutex: ReentrantLock = new ReentrantLock(true)

  /**
   * Constructs a report of performance metrics of task's work
   * @return Constructed performance report
   */
  def getReport = {
    logger.info(s"Start preparing a report of performance for task: $taskId of output module\n")
    mutex.lock()
    val bytesOfInputEnvelopes = inputEnvelopesPerStream.map(x => (x._1, x._2.map(_.sum).sum)).head._2
    val bytesOfOutputEnvelopes = outputEnvelopesPerStream.map(x => (x._1, x._2.map(_._2.sum).sum)).head._2
    val inputEnvelopesTotalNumber = inputEnvelopesPerStream.map(x => (x._1, x._2.size)).head._2
    val inputElementsTotalNumber = inputEnvelopesPerStream.map(x => (x._1, x._2.map(_.size).sum)).head._2
    val outputEnvelopesTotalNumber = outputEnvelopesPerStream.map(x => (x._1, x._2.size)).head._2
    val outputElementsTotalNumber = outputEnvelopesPerStream.map(x => (x._1, x._2.map(_._2.size).sum)).head._2
    val inputEnvelopesSize = inputEnvelopesPerStream.flatMap(x => x._2.map(_.size))
    val outputEnvelopesSize = outputEnvelopesPerStream.flatMap(x => x._2.map(_._2.size))

    val performanceReport =
      s"""{
         |"pm-datetime" : "${Calendar.getInstance().getTimeInMillis}",
                                                                      |"task-id" : "$taskId",
                                                                                             |"host" : "$host",
                                                                                                               |"input-stream-name" : "$inputStreamName",
                                                                                                                                                         |"total-input-envelopes" : $inputEnvelopesTotalNumber,
                                                                                                                                                                                                                |"total-input-elements" : $inputElementsTotalNumber,
                                                                                                                                                                                                                                                                     |"total-input-bytes" : $bytesOfInputEnvelopes,
                                                                                                                                                                                                                                                                                                                    |"average-size-input-envelope" : ${if (inputElementsTotalNumber != 0) inputElementsTotalNumber / inputEnvelopesTotalNumber else 0},
                                                                                                                                                                                                                                                                                                                                                                                                                                                        |"max-size-input-envelope" : ${if (inputEnvelopesSize.nonEmpty) inputEnvelopesSize.max else 0},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |"min-size-input-envelope" : ${if (inputEnvelopesSize.nonEmpty) inputEnvelopesSize.min else 0},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |"average-size-input-element" : ${if (inputElementsTotalNumber != 0) bytesOfInputEnvelopes / inputElementsTotalNumber else 0},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |"output-stream-name" : "$outputStreamName",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |"total-output-envelopes" : $outputEnvelopesTotalNumber,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |"total-output-elements" : $outputElementsTotalNumber,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |"total-output-bytes" : $bytesOfOutputEnvelopes,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |"average-size-output-envelope" : ${if (outputEnvelopesTotalNumber != 0) outputElementsTotalNumber / outputEnvelopesTotalNumber else 0},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |"max-size-output-envelope" : ${if (outputEnvelopesSize.nonEmpty) outputEnvelopesSize.max else 0},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |"min-size-output-envelope" : ${if (outputEnvelopesSize.nonEmpty) outputEnvelopesSize.min else 0},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |"average-size-output-element" : ${if (outputEnvelopesTotalNumber != 0) bytesOfOutputEnvelopes / outputElementsTotalNumber else 0},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |"uptime" : ${(System.currentTimeMillis() - startTime) / 1000}
      }
    """.stripMargin

    logger.debug(s"Reset variables for performance report for next reporting\n")
    inputEnvelopesPerStream = mutable.Map(inputStreamName -> mutable.ListBuffer[List[Int]]())
    outputEnvelopesPerStream = mutable.Map(outputStreamName -> mutable.Map[String, mutable.ListBuffer[Int]]())

    mutex.unlock()

    performanceReport
  }
}